### ISSUE TITLE
Does it work under CPU? Can I use the Latent Consistency Model? Is it possible to image to image? Is there an example

### ISSUE THREAD

**Issue by mingooglegit** [PRIS-CV/DemoFusion#1]
Does it work under CPU? Can I use the Latent Consistency Model? Is it possible to image to image? Is there an example

**Comment by RuoyiDu** [comment]
- It works on CPU but will be much slower. You can have a try by set "cuda" to "cpu" and "float16" to "float32".
- I don't think it can work as well on LCM as it does on SD. As DemoFusion relies on the interaction at each time-steps.
- Yes, you can change the output of Phase #1 to encoded real images. But as we discussed in the paper, the results are not that satisfactory.
