### ISSUE TITLE
How to perform the image "super-resolution"

### ISSUE THREAD

**Issue by zhangn77** [PRIS-CV/DemoFusion#2]
How to perform the image "super-resolution" as the project page "Upscaling Real Images" said;
And if I only want to upscaling the SD-generated image, will the pipeline be different?

**Comment by Laidawang** [comment]
I want to ask if you know how to do this?

**Comment by HanLiii** [comment]
> Do you know how to do this?

Do you find out a way to use demofusion to do image upscaling?

**Comment by zhangn77** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到。会尽快查看会予以回复~祝您生活愉快！
