### ISSUE TITLE
中文画图能力如何？

### ISSUE THREAD

**Issue by xxm1668** [PRIS-CV/DemoFusion#24]

**Comment by RuoyiDu** [comment]
Q: 中文画图能力如何？
How is the performance of using Chinese Prompt?

A: 作为training-free的方法，DemoFusion对中文prompt的理解能力与所使用的LDM（例如SDXL）一致。
As a training-free approach, DemoFusion's comprehension of Chinese prompts is consistent with the LDM used (e.g., SDXL).

**Comment by xxm1668** [comment]
tanks

**Comment by xxm1668** [comment]
thanks
