### ISSUE TITLE
DemoFusion Controlnet pipeline?

### ISSUE THREAD

**Issue by garg-aayush** [PRIS-CV/DemoFusion#26]
Thank you for sharing the codebase for the Demofusion paper. The paper and the approach you all followed is great. 

I see in the paper, you shared the SDXL + controlnet results for Demofusion. However, I am unable to find the controlnet pipeline in the codebase. When do you plan to release it?

**Comment by RuoyiDu** [comment]
Hi @garg-aayush, DemoFusion ControlNet pipeline is available now. Have fun :)

**Comment by garg-aayush** [comment]
Thanks a lot @RuoyiDu
