### ISSUE TITLE
Errata in the paper

### ISSUE THREAD

**Issue by ttulttul** [PRIS-CV/DemoFusion#28]
Your formula for c1 in the paper is:

c1 = ((1 + cos(2*pi*t / T)) / 2) ** alpha_1

However, in your code, you do not multiply pi by 2. If you use 2*pi in the cosine function, then over the interval of t=[0,T], the cosine function will cause c1 to vary from 1, to 0, and then back to 1 again, which is definitely not what you want.

**Comment by RuoyiDu** [comment]
Haha yes. Sorry for the mistake I made in my haste, I've spotted this and will fix it in the next version. Thank you for the thoughtful reminder!

**Comment by ttulttul** [comment]
No worries. It's a really interesting technique you've found. I am working on a ComfyUI-native implementation.
