### ISSUE TITLE
Generated images looks a bit grainy even after increase cosine scale 3

### ISSUE THREAD

**Issue by KaustubhPatange** [PRIS-CV/DemoFusion#36]
So I've trained a custom model that generates a cartoon scenery. Following are the output generated from text2image -> DemoFusion,

| Text2Image | DemoFusion |
|--|--|
| <img src="https://github.com/PRIS-CV/DemoFusion/assets/22119598/66d5f37a-e5cf-41d0-a974-fec7e5666173" /> | <img src="https://github.com/PRIS-CV/DemoFusion/assets/22119598/c4c418f7-a4fa-4c00-92b4-cc11df626da5" /> |

As you can see the output looks a bit grainy and not so sharp. I tried increasing cosine scales 1,2,3 and also decreasing stride but the effect is still the same. What can I do to make it more similar to the original image and remove the blurry/grainy effect?

The current parameters are stride=64, sigma=0.8, cosine_scale_1=3.0, cosine_scale_2=3.0, cosine_scale_3=3.0.

**Comment by RuoyiDu** [comment]
Hi @KaustubhPatange, we have not tested DemoFusion's performance on custom models. Because DemoFusion relies on a prior for image crops, fine-tuning the custom model on specific data may weaken this prior and lead to performance degradation. I guess that's why.
