### ISSUE TITLE
does it support sdxl_turbo?

### ISSUE THREAD

**Issue by betterze** [PRIS-CV/DemoFusion#43]
Dear DemoFusion team,

Thank you for sharing this great work, I really like it.

Does it support SDXL_turbo? 

Thank you for your help.

Best Wishes,
Zongze

**Comment by sebaxakerhtc** [comment]
@betterze 
I tried some models, and have a good results.
"Guidance Scale" for Turbo models is recommend 1-2, but it doesn't have a good results. I play with 5-6.

**Comment by betterze** [comment]
get it. thx a lot.

**Comment by khs8727** [comment]
@sebaxakerhtc 
Can you explain the details about how to get the good results from turbo model?
I tried with the model below with sdxl pipeline code. (https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py)
https://huggingface.co/docs/diffusers/using-diffusers/sdxl_turbo#load-model-checkpoints
with num_inference_steps 1~4

The result images were full of noises..

**Comment by sebaxakerhtc** [comment]
> with num_inference_steps 1~4

It's very low value for MULTIdiffusion. You should be trying Lighting model? I'm not tried yet.
I don't like any Turbo or Lighting models at all. Original SDXL based models have much much better results, especially about details. IMO

Turbo works good at 8-10 steps, CFG 4-5
I play with DreamShaperXL

![settings](https://github.com/PRIS-CV/DemoFusion/assets/32651506/802ca813-512a-4468-9cf5-d21f1342e97e)

Feel free to play with settings!
![orig](https://github.com/PRIS-CV/DemoFusion/assets/32651506/a72effe1-f462-4a3c-9664-e201ff5385c5)
![2048](https://github.com/PRIS-CV/DemoFusion/assets/32651506/08fdd1ed-eac7-40bc-b3a1-9164a66ed0e1)
