### ISSUE TITLE
Why i always have the connect error?

### ISSUE THREAD

**Issue by Jll0716** [PRIS-CV/DemoFusion#47]
Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-xl-base-1.0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f01298ab5e0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: f9389355-d610-413f-a89f-d9163bec16c5)').
Will try to load from local cache.

**Comment by Bin7007** [comment]
Pls did you solve this problem, I'm also getting the same error
