### ISSUE TITLE
image upscale

### ISSUE THREAD

**Issue by Laidawang** [PRIS-CV/DemoFusion#6]
Please tell me how to input the image as described in the paper to make it super resolution? At the same time, is there a parameter similar to strength to control the change? In your project, I feel that the change seems too big for works like SR.

**Comment by RuoyiDu** [comment]
Hi @Laidawang. Thanks to our community, many img2img demos can be found now, e.g., https://huggingface.co/spaces/radames/Enhance-This-DemoFusion-SDXL. 

DemoFusion is proposed for hig-resolution generation, and as a tuning-free method, its capability for img2img is strongly correlated with the SDXL's training data distribution and will show a significant bias. Pleaseregard this "upscaling" as a side application of text+image based generation and have fun!

**Comment by HanLiii** [comment]
> Please tell me how to input the image as described in the paper to make it super resolution? At the same time, is there a parameter similar to strength to control the change? In your project, I feel that the change seems too big for works like SR.

I see there is a image_lr in the __call___ function, this should be the input image param. But I don't know the range of image_lr. You can find it at line 694, [pipeline_demofusion_sdxl.py](https://github.com/PRIS-CV/DemoFusion/blob/main/pipeline_demofusion_sdxl.py)


image_lr (torch.FloatTensor, optional, , defaults to None):
Low-resolution image input for upscaling. If provided, DemoFusion will encode it as the initial latent representation.
