### ISSUE TITLE
Supported resolutions and i2i

### ISSUE THREAD

**Issue by green-anger** [PRIS-CV/DemoFusion#7]
Most of the examples you provided are squares, but some have different orientations, portrait and landscape. What are the supported resolutions (or in this case better say about aspect ratio), are they the same as for [SDXL](https://arxiv.org/abs/2307.01952)?

The seconds part is mostly a dup from other issues, I just want to expand it a bit. Is it possible to generate an image with a SDXL model and then use it as input in DemoFusion to either increase level of detail (keep the same resolution) or upscale? Can DemoFusion be considered upscaling + ControlNet Tile model replacement?

**Comment by RuoyiDu** [comment]
Hi @green-anger. Thanks to our community, many img2img demos can be found now, e.g., https://huggingface.co/spaces/radames/Enhance-This-DemoFusion-SDXL.

As for the supported resolution, any aspect ratios are supported, but you need to make sure the larger one of `height` and `width` has to be divisible by 1024. You can understand it as only integer times upscaling is supported.
