### ISSUE TITLE
wrong server ip for gradio demo and no gradio installed

### ISSUE THREAD

**Issue by Zdeto** [PRIS-CV/DemoFusion#8]
Hi :)
I tried to run locally the gradio_demo.py and run into some errors.
ModuleNotFoundError: No module named 'gradio'

So I had to activate the venv and manually install gradio.

Then when I run again:
ERROR:    [Errno 10049] error while attempting to bind on address ('114.113.235.51', 8890): the requested address is not valid in its context

And I had to edit the py file and change the server address to 127.0.0.1 and it run. I still get this:
Error caught was: No module named 'triton'
but it seems to work now :)

**Comment by RuoyiDu** [comment]
Hi @Zdeto, thanks for reminding us! I tested the demo on a remote device and forgot to set the ip to default. I have fixed this issue.
